return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 23,
  height = 27,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 6,
  nextobjectid = 60,
  properties = {},
  tilesets = {
    {
      name = "main_hub",
      firstgid = 1,
      filename = "../tilesets/main_hub.tsx",
      exportfilename = "../tilesets/main_hub.lua"
    },
    {
      name = "hub_objects",
      firstgid = 101,
      filename = "../tilesets/hub_objects.tsx",
      exportfilename = "../tilesets/hub_objects.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 27,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 65, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 44, 70, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 75, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 54, 80, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 85, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 64, 90, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 95, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 100, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 13, 13, 13, 13, 13,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 33, 33, 33, 33, 33,
        0, 0, 0, 0, 0, 32, 33, 33, 33, 23, 23, 23, 23, 23, 33, 33, 33, 34, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 44, 2, 3, 4, 32, 33, 33, 33, 34, 2, 3, 4, 42, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 54, 2, 3, 4, 42, 43, 43, 43, 44, 2, 3, 4, 52, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 64, 2, 3, 4, 52, 53, 51, 53, 54, 2, 3, 4, 62, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 62, 63, 63, 63, 64, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        13, 13, 13, 13, 13, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 13, 13, 13, 13, 13,
        33, 33, 33, 33, 33, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 33, 33, 33, 33, 33,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 26, 0, 0, 0, 0,
        13, 13, 13, 13, 23, 23, 36, 35, 23, 23, 23, 23, 23, 23, 23, 36, 35, 23, 23, 13, 13, 13, 13,
        33, 33, 33, 33, 33, 36, 0, 0, 35, 33, 33, 33, 33, 33, 36, 0, 0, 35, 33, 33, 33, 33, 33,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 80,
          width = 440,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          class = "",
          shape = "rectangle",
          x = 680,
          y = 360,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          class = "",
          shape = "rectangle",
          x = 360,
          y = 400,
          width = 200,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          class = "",
          shape = "rectangle",
          x = 200,
          y = 360,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 680,
          width = 40,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          class = "",
          shape = "polygon",
          x = 200,
          y = 1000,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 80, y = -80 },
            { x = 160, y = 0 }
          },
          properties = {}
        },
        {
          id = 19,
          name = "",
          class = "",
          shape = "polygon",
          x = 560,
          y = 1000,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 80, y = -80 },
            { x = 160, y = 0 }
          },
          properties = {}
        },
        {
          id = 20,
          name = "",
          class = "",
          shape = "polygon",
          x = 720,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = 40 },
            { x = 40, y = 0 }
          },
          properties = {}
        },
        {
          id = 21,
          name = "",
          class = "",
          shape = "polygon",
          x = 200,
          y = 880,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -40, y = 40 },
            { x = -40, y = 0 }
          },
          properties = {}
        },
        {
          id = 25,
          name = "",
          class = "",
          shape = "rectangle",
          x = 360,
          y = 360,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          class = "",
          shape = "rectangle",
          x = 560,
          y = 360,
          width = 0,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          class = "",
          shape = "polygon",
          x = 240,
          y = 120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = -40, y = 0 },
            { x = -40, y = 40 }
          },
          properties = {}
        },
        {
          id = 46,
          name = "",
          class = "",
          shape = "polygon",
          x = 680,
          y = 120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = 40 },
            { x = 40, y = 0 }
          },
          properties = {}
        },
        {
          id = 50,
          name = "",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 680,
          width = 200,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 880,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 1000,
          width = 400,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          class = "",
          shape = "rectangle",
          x = 520,
          y = 1000,
          width = 400,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          class = "",
          shape = "rectangle",
          x = 760,
          y = 680,
          width = 160,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 320,
          width = 200,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 160,
          width = 200,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 200,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          class = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 200,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_under",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 47,
          name = "",
          class = "",
          shape = "rectangle",
          x = 340,
          y = 760,
          width = 240,
          height = 160,
          rotation = 0,
          gid = 101,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 27,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 400,
          y = 1080,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 920,
          y = 920,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = -40,
          y = 920,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = -40,
          y = 600,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 920,
          y = 600,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = -40,
          y = 240,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "transition",
          class = "",
          shape = "rectangle",
          x = 920,
          y = 240,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "interactable",
          class = "",
          shape = "rectangle",
          x = 440,
          y = 480,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "savepoint",
          class = "",
          shape = "rectangle",
          x = 440,
          y = 600,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 880,
          width = 180,
          height = 140,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "interactable",
          class = "",
          shape = "rectangle",
          x = 800,
          y = 880,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 35,
          name = "south",
          class = "",
          shape = "point",
          x = 460,
          y = 1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "west1",
          class = "",
          shape = "point",
          x = 40,
          y = 960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "west2",
          class = "",
          shape = "point",
          x = 40,
          y = 640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "west3",
          class = "",
          shape = "point",
          x = 40,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "east1",
          class = "",
          shape = "point",
          x = 880,
          y = 960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "east2",
          class = "",
          shape = "point",
          x = 880,
          y = 640,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "east3",
          class = "",
          shape = "point",
          x = 880,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "spawn",
          class = "",
          shape = "point",
          x = 460,
          y = 680,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
